# os/.cargo/config
[build]
# https://doc.rust-lang.org/nightly/rustc/platform-support.html
# Bare RISC-V (riscv64gc = RV64IMAFDC ISA)
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
  "-Clink-arg=-Tkernel/src/linker.ld",
  "-Cforce-frame-pointers=yes",
]
