[package]
authors = ["curry <VanishingDante@gmail.com>"]
edition = "2018"
name = "kernel"
version = "0.1.0"

# [lib]
# crate-type = ["staticlib"]
# name = "kernel"
# path = "src/lib.rs"

[dependencies]
bitflags = "1.2.1"
bitvec = {default-features = false, version = "0.19.4"}
lazy_static = {version = "1.4.0", features = ["spin_no_std"]}
riscv = {git = "https://github.com/rust-embedded/riscv", features = ["inline-asm"]}
spin = "0.7.0"
static_assertions = "1.1.0"
volatile = "0.4.2"

[profile.dev]
# abort on panic instead, disables the generation of unwinding symbol information
debug = true
panic = "abort"

[profile.release]
# abort on panic instead, disables the generation of unwinding symbol information
debug = true
panic = "abort"
