cargo-features = ["per-package-target"]

[package]
name = "kernel"
version = "0.1.0"
authors = ["curry <VanishingDante@gmail.com>"]
edition = "2024"
forced-target = "riscv64imac-unknown-none-elf"

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
fdt-raw = "0.3.0"
frame-allocator = { path = "../frame-allocator" }
buddy-heap = { path = "../buddy-heap" }
heapless = "0.9"
paging = { path = "../paging", default-features = false }
riscv = "0.16.0"
sbi-rt = "0.0.4"
sbi-spec = "0.0.9"
spin = "0.10.0"
uart_16550 = "0.4"

