[build]
# https://doc.rust-lang.org/nightly/rustc/platform-support.html
# Bare RISC-V (riscv64gc = RV64IMAFDC ISA)
rustflags = ['-Clink-arg=-Tsrc/kernel.ld', '--cfg=riscv64', '-Ctarget-feature=-c']
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -s -nographic -no-reboot -machine virt -cpu rv64 -d guest_errors,unimp -smp 1 -m 128M -drive if=none,format=raw,file=hdd.dsk,id=foo -device virtio-blk-device,scsi=off,drive=foo -serial mon:stdio -bios none -device virtio-rng-device -device virtio-gpu-device -device virtio-net-device -device virtio-tablet-device -device virtio-keyboard-device -kernel "
